# -*- coding: utf-8 -*-
"""Final Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuAT8l_ttG3DS66vOulvVHfvp86Iish5

Multiple Myeloma [MM], a monoclonal plasma cell malignancy compromises 1-2% of all cancers and about 10-20% of all hematological malignancies. Every year, there are nearly 35,000 new patients who developed the disease in the United States, and nearly 13,000 people who die from. Many patients initially have a condition called Monoclonal Gammopathy of Undetermined Significance[MGUS], which increases the risk of developing MM to an average of 1% per year, depending on specific monoclonal proteins. Smoldering MM[SMM] increases the risk to an average of 10% per year and nearly 75% after 15 years. The question raised by this analysis is whether we can build a predictive model to help determine which patients with MGUS and SMM are likely to transform to multiple myeloma[MM]. Nieto et al, J Clin Haematology.2023.
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC


from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_transformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, precision_score
from sklearn.metrics import accuracy_score, roc_auc_score,ConfusionMatrixDisplay
from sklearn.metrics import f1_score, recall_score, precision_recall_curve, roc_curve
import time

from sklearn import set_config
set_config(display='diagram')

import warnings
warnings.filterwarnings('ignore')

from google.colab import files
import pandas as pd
import io

uploaded= files.upload()

file_name= list(uploaded.keys())[0]
df= pd.read_csv(io.BytesIO(uploaded[file_name]))
df.head()

df.info()

df.describe()

"""Average patient's age is 70, range 34 to 96 years which is consistent with these conditions occurring mostly in older patients. The sex distribution is balanced approx 50% each. The percentages of disease versus healthy are 29% healthy and 71% disease. This is the reason I used class_weight='balance'.
The monoclonal protein level mean=2.29, max=36.4, there is large variability std=2.7. Likely strongly skewed because of many low values and few extremily high values. This variable potentially can become an important predictive biomarker.

The kappa/lambda light chain ratio. mean 196, median 4.97, max= 11208. The variable is extremily skewed, likely because of the presence of major outliers and possible severe plasma disorders. Kidney function is measure with the creatinine level. The mean 1.61, max= 14.4, the high values indicate renal impairment, myeloma kidney disease. The distribution is also skewed.

The calcium level, mean 9.85, max= 17. Elevated calcium level indicate advanced myeloma, bone involvement. Hypercalcemia is part of the CRAB criteria.
Bone marrow plasma cell percentage, mean 52%, large spread std 29. This is likely a very important predictor.

**EXPLORE THE DISTRIBUTION OF THE DATASET**

The main purpose of this code is to explore the numerical features, detect outliers, check spread/variablility, compare distributions across variables, identify skewed data and performing exploratory data analysis (EDA).
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

num_column_1st= [
    col for col in df.columns
    if np.issubdtype(df[col].dtype, np.number) and not df[col].isnull().all()]

if len(num_column_1st)==0:
    raise ValueError("No numerical columns to plot")

n_cols_per_row= 4
n_rows= (len(num_column_1st)+n_cols_per_row-1)//n_cols_per_row

fig, axes= plt.subplots(
    nrows= n_rows,
    ncols= n_cols_per_row,
    figsize=(14,8))


axs_flat= np.array(axes).flatten()

for name, ax in zip(num_column_1st, axs_flat):
    sns.boxplot(x=df[name], ax=ax)
    ax.set_title('Distribution of the data')


for i in range(len(num_column_1st), len(axs_flat)):
    fig.delaxes(axs_flat[i])

plt.tight_layout()
plt.show()

"""The distribution of LDH ( lactate dehydrogenase) which is a marker of cell turnover/ aggressive disease has outliers. Very high LDH may indicate aggressive myeloma.
The distribution of K/L ratio max 11208 also has outliers and  represents patients with very aggressive disease.

**EXPLORE THE DISTRIBUTION OF THROUGH BAR PLOTS**

This code creates a grid of histograms for all numerical variables in the dataset to visualize the distributions. It helps to understand the shape of the data, skewness, spread, frequency patterns, possible outliers.
"""

fig, axs = plt.subplots(nrows=4, ncols=4, figsize=(14, 14))

axs_flat = axs.flatten() if axs.ndim > 1 else [axs]

for name, ax in zip(num_column_1st, axs_flat):
    sns.histplot(data=df, x=name, ax=ax, multiple='stack', stat='percent')
    ax.tick_params(axis='x', rotation=45, labelsize=8)

# hide unused plots
for ax in axs_flat[len(num_column_1st):]:
    ax.set_visible(False)

fig.suptitle('Distribution of Numeric Features', y=1.02, fontsize=20)
plt.tight_layout()
plt.subplots_adjust(top=0.92)
plt.show()

"""The histograms identify the normal distribution such as age, creatinine and calcium. We could also see the bimodal distributions and sparse variables.

**CORRELATION MATRIX OF THE NUMERICAL FEATURES**

The advantage of the correlation heatmap is that it allows to understand the relationship between variables, whether variables increase or decrease together, multicollinearity and important feature associations. It explores the data before machine learning.
"""

plt.figure(figsize=(10,10))
corr = df[num_column_1st].select_dtypes(include='number').corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Numerical Features')
plt.show()

"""There is strong correlation in the heatmap between percentage of plasma cells and presence of lytic lesions. This relationship is clinically significant because it represents either MGUS progression, SMM transformation or myeloma severity.
There is also strong correlation between plasma cells and presence or absence of disease.

"""

g=sns.pairplot(df[num_column_1st], height= 2.5)

g.fig.suptitle('Pairplot of Numerical Features', y=1.02, fontsize=20)
plt.show()

"""The distribution of M spike and K/L ratio are skewed, these variables are not normally distributed and often appear right skewed in clinical datasets. There is also positive correlation between plasma cells and M spike which is consistent with progression of the disease. The presence of high M  spike associated with high plasma cells, the clustering of transformed MM patients, may suggest a stronger disease burden. There are also clusters that represent possible patients subtypes and different disease stages.

**CATEGORICAL FEATURES INVESTIGATION**

The countplots assist with the interpretation of categorical distributions, identify imbalance, detect data cleaning problems, visualize patient subgroup frequencies and guide preprocessing before ML modeling.
"""

cat_column_1st=[]
for icol in df.columns:
    if df[icol].dtypes =='object' and not icol.startswith('Unnamed'):
        cat_column_1st.append(icol)
print(cat_column_1st)

fig,axs= plt.subplots(nrows=4,ncols=2,figsize=(25,25))
for name,ax in zip(cat_column_1st,axs.flatten()):
    sns.countplot(data=df,x=name,ax=ax)
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, horizontalalignment='right',fontsize=12)

for ax in axs.flatten()[len(cat_column_1st):]:
    ax.set_visible(False)

fig.tight_layout()
fig.suptitle('Distribution of Categorical Features', y=1.02, fontsize=30)
plt.show()

"""Clinically meaninful patterns can be identified in the distribution of race , and sex. Multiple myeloma is more common among caucasian patients but tend to be more aggressive among African Americans."""







"""**ENGINIERING FEATURES**

Feature engineering is important because it helps interpret the model patterns more easily, improve prediction accuracy, reduce noise, capture important relationships and improve interpretability.
"""

print(df.columns.tolist())

cols = ['age', 'sex0=M,1=F)',
        'K/L ratio',
        'M spike',
        'cytogenetics 1=low,2=intermediate,3=high,4=normal',
        'TP53 yes=0,No =1 (IS DELETION PRESENT)',
        'disease=0 healthy=1',
        'race(1=white 2=Black, 3=Hispanic, 4=other',
        'Transformed to MM yes 0 no 1']

missing = [col for col in cols if col not in df.columns]
print(" Missing columns:")
print(missing)

cols = ['age', 'sex0=M,1=F)',
        'K/L ratio',
        'M spike',
        'cytogenetics 1=low,2=intermediate,3=high,4=normal',
        'TP53 yes=0,No =1 (IS DELETION PRESENT)',
        'disease=0 healthy=1',
        'race(1=white 2=Black, 3=Hispanic, 4=other',
        'Transformed to MM yes 0 no 1']
cols_existing = [col for col in cols if col in df.columns]
DF=df[cols_existing]
print(DF.shape)
DF.head()

df=df.rename(columns={
'sex0=M,1=F)': 'sex',
'cytogenetics 1=low,2=intermediate,3=high,4=normal': 'cytogenetics',
'TP53 yes=0,No =1 (IS DELETION PRESENT)': 'TP53',
'disease=0 healthy=1': 'disease',
'race(1=white 2=Black, 3=Hispanic, 4=other': 'race',
})

Df=df[['age','sex','K/L ratio','M spike','cytogenetics', 'TP53','disease', 'race']]
print(Df.shape)
Df.head()

DF=df[['age','sex','K/L ratio', 'M spike','cytogenetics', 'TP53', 'disease', 'race']]

print('Missing values in DF:')
print(DF.isnull().sum())

print('\nData types in DF:')
print(DF.dtypes)

"""This code prepares the data before machine learning. It builds a preprocessing pipeline. This code cleans missing values, scales numeric variables, converts categorical variables into machine- readable columns, and prepares the dataset for training a model."""

from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

print(DF.columns.tolist())
numerical_impute_scale_cols= ['K/L ratio', 'M spike']
numerical_scale_only_cols= ['age', 'sex']

categorical_impute_ohe_cols= [
    'cytogenetics',
    'TP53'
]
categorical_ohe_only_cols= ['race'] # Removed 'disease' as it's the target variable

all_cols= (
    numerical_impute_scale_cols +
    numerical_scale_only_cols +
    categorical_impute_ohe_cols +
    categorical_ohe_only_cols

)

missing= [col for col in all_cols if col not in DF.columns]
print("Missing columns:", missing)


if len(missing) >0:
    raise ValueError("Some column names do not match DF.columns")

numerical_impute_scale_pipeline= Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])
numerical_scale_only_pipeline= Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_impute_ohe_pipeline= Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])
categorical_ohe_only_pipeline= Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))

])
column_transformer= ColumnTransformer(
    transformers=[
        ('num_impute_scale', numerical_impute_scale_pipeline, numerical_impute_scale_cols),
        ('num_scale_only', numerical_scale_only_pipeline, numerical_scale_only_cols),
        ('cat_impute_ohe', categorical_impute_ohe_pipeline, categorical_impute_ohe_cols),
        ('cat_ohe_only', categorical_ohe_only_pipeline, categorical_ohe_only_cols)
    ],
    remainder='drop'
)

"""This code trains 3 classification models to predict disease. It also splits the data into training and testing sets while keeping the same proportion of disease classes in both sets."""

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

# Define X and y using the 'disease' column as target
X = DF.drop('disease', axis=1)
y = DF['disease']

# Perform train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Ensure y_train and y_test are of integer type
y_train = y_train.astype(int)
y_test = y_test.astype(int)

X_train_transformed = column_transformer.fit_transform(X_train)
X_test_transformed = column_transformer.transform(X_test)

log_model = LogisticRegression(
    class_weight='balanced',
    solver= 'liblinear',
    max_iter=1000)


log_model.fit(X_train_transformed, y_train)

svm_model= SVC(
    class_weight='balanced',
    probability=True)

svm_model.fit(X_train_transformed, y_train)

custom_weights= {0:1, 1:10}

custom_model = LogisticRegression(
    class_weight=custom_weights,
    solver='liblinear',
    max_iter=1000)


custom_model.fit(X_train_transformed, y_train)

#Predictions
y_pred_log= log_model.predict(X_test_transformed)
y_pred_svm = svm_model.predict(X_test_transformed)
y_pred_custom= custom_model.predict(X_test_transformed)

print("Logistic Regression Results")
print(classification_report(y_test, y_pred_log,zero_division=0))

print("SVM Results with Class Weights:")
print(classification_report(y_test, y_pred_svm, zero_division=0))

print("Custom Logistic Regression Results:")
print(classification_report(y_test, y_pred_custom, zero_division=0))

"""The weighted logistic regression gives more importance to class 0, so it may be better for identyfying high-risk patients. However, if precision drops too much, it may also label many low risk patients as high-risk. Therefore, the best model should be selected based on the clinical priority: avoiding missed high-risk patients versus avoiding false alarms.

The logistic regression model performed reasonably well overall with 75% accuracy. Recall= 0.83, the model identified 83% of true class 0 patients. This is good clinically because the model is missing relatively few high-risk/ disease patients. Precision 0.54, only 54% of patients predicted a class 0 were actually class 0. This means the model produces some false positives.
This model favors sensitivity/recall over precision, which may be acceptable in medical screening settings where missing a high-risk patient is more concerning than generating additional follow-up evaluations.

The SVM model performed better overall than logistic regression. The recall for class 1 increased to 91%, precision slightly improved to 57%, accuracy improved to 78% and F1 score class 1 improved to 0.70. The SVM detected almost all true class 1 patients while mantaining moderate precision.
This is likely the strongest model among the three because it achieved the highest recall for class 1, the best F1 score, and the best overall accuracy.
The model appears highly sensitive for detecting disease/high-risk patients, making it clinically useful when the goal is minimizing missed progression cases.

The Custom Logistic Regression, this model heavily prioritized class 0 detection. The recall became extremily high 96%, precision dropped substantially 40%, accuracy dropped  to 57%. This means that the model almost never misses class 0 patients, but labels many class 1 patients incorrectly as class 0. Very high false positive rate.
This model may be useful if the absolute priority is avoiding missed disease cases. However, the large number of false positives could lead to unnecessary testing, anxiety or interventions.
"""



"""**LOGISTIC REGRESSION**

This code trains and evaluates a Logistic Regression classification model and then visualizes its performance using evaluation metrics, confusion matrix, ROC curve.
"""

import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score, f1_score,precision_score,recall_score,roc_auc_score,ConfusionMatrixDisplay, roc_curve)
from sklearn.model_selection import train_test_split
import pandas as pd
import time

#Fit transformer on training data only
X_train_transformed_local = column_transformer.fit_transform(X_train)
X_test_transformed_local = column_transformer.transform(X_test)

logreg= LogisticRegression(
    class_weight='balanced',
    solver='liblinear',
    max_iter=1000)

start= time.time()
logreg.fit(X_train_transformed_local, y_train)
stop= time.time()

fit_time= str(round(stop-start,2)) + ' seconds'

y_pred= logreg.predict(X_test_transformed_local)
y_pred_proba= logreg.predict_proba(X_test_transformed_local)[:,1]

results_df= pd.DataFrame(
    columns=('Fit Time', 'Accuracy','ROC_AUC', 'F1', 'Precision','Recall'))

results_df.loc['Logistic Regression', 'Fit Time'] = fit_time
results_df.loc['Logistic Regression', 'Accuracy'] = accuracy_score(y_test, y_pred)
results_df.loc['Logistic Regression', 'ROC_AUC'] = roc_auc_score(y_test, y_pred_proba)
results_df.loc['Logistic Regression', 'F1'] = f1_score(y_test, y_pred, zero_division=0)
results_df.loc['Logistic Regression', 'Precision'] = precision_score(y_test, y_pred, zero_division=0)
results_df.loc['Logistic Regression', 'Recall'] = recall_score(y_test, y_pred, zero_division=0)


print(results_df.loc['Logistic Regression'])

ConfusionMatrixDisplay.from_predictions(y_test, y_pred)
plt.title('Confusion Matrix- Logistic Regression')
plt.show()

fpr,tpr,thresholds = roc_curve(y_test, y_pred_proba)

plt.plot(fpr, tpr,'--o', label= f"Logistic Regression(AUC={results_df.loc['Logistic Regression', 'ROC_AUC']:.2f})")
plt.plot([0,1],[0,1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve- Logistic Regression')
plt.legend()
plt.show()

"""I used class_weight='balanced', to adjust for class imbalance. If disease cases are fewer the model gives them more importance.
The Logistic regression model demonstrated good discrimination between disease and non-disease patients. The ROC curve indicates that the model performs substantially better than random classification, while the confusion matrix suggest the model identifies most disease cases with moderate false positive rates.

**K-Nearest Neighbors **
"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (ConfusionMatrixDisplay, accuracy_score, roc_auc_score, f1_score, precision_score, recall_score, roc_curve)

import pandas as pd
import matplotlib.pyplot as plt
import time


knn= KNeighborsClassifier(n_neighbors=5, weights='distance')
start= time.time()
knn.fit(X_train_transformed_local, y_train)
stop= time.time()

fit_time= str(round(stop-start,2)) + ' seconds'

y_pred_knn= knn.predict(X_test_transformed_local)
y_proba_knn= knn.predict_proba(X_test_transformed_local)


ConfusionMatrixDisplay.from_predictions(y_test, y_pred_knn, display_labels=knn.classes_)
plt.title("Confusion Matrix for Multiple Myeloma Prediction KNN")
plt.show()


results_df= pd.DataFrame(
    columns=['Fit Time', 'Accuracy','ROC_AUC', 'F1', 'Precision','Recall'])


results_df.loc['KNN', 'Fit Time'] = fit_time
results_df.loc['KNN', 'Accuracy'] = accuracy_score(y_test, y_pred_knn)
results_df.loc['KNN', 'F1'] = f1_score(y_test, y_pred_knn, zero_division=0)
results_df.loc['KNN', 'Precision'] = precision_score(y_test, y_pred_knn, zero_division=0)
results_df.loc['KNN', 'Recall']= recall_score(y_test, y_pred_knn, zero_division=0)


if len(knn.classes_)==2:
   positive_class_index= list(knn.classes_).index(1)
   y_score_knn= y_proba_knn[:,positive_class_index]

   results_df.loc['KNN', 'ROC_AUC'] = roc_auc_score(y_test, y_score_knn)


   fpr,tpr,thresholds = roc_curve(y_test, y_score_knn)

   plt.figure(figsize=(10,6))
   plt.plot(fpr, tpr, label= f"KNN(AUC={results_df.loc['KNN', 'ROC_AUC']:.2f})")
   plt.plot([0,1],[0,1], 'k--')
   plt.xlabel('False Positive Rate')
   plt.ylabel('True Positive Rate')
   plt.title('ROC Curve- K Nearest Neighbors')
   plt.legend()
   plt.show()

else:
    results_df.loc['KNN', 'ROC_AUC'] = None
    print("ROC AUC skipped because only one class is present.")
print(results_df.loc['KNN'])

"""The ROC curve bends strongly  toward the upper-left corner. That means, there is a high positive rate and relatively low false positive rate. The model performs far better than random guessing. The dashed diagonal line represents random classification. The curve is well above that line. The model has strong predictive power.

The KNN model demonstrated strong overall performance with an accuracy of 82.5% and an ROC_AUC of 0.88 indicating excellent discrimination between disease and nondisease patients. The confusion matrix showed that the model correctly identified most patients while mantaining relatively few false positives and false negatives. Compared with previous models, KNN achieved higher precision and overall accuracy, although recall was somewhat lower than the SVM model. These findings suggest that KNN provides a balanced and clinically meaningful approach for predicting multiple myeloma progression while limiting unnecessary false positive classifications.

**SUPPORT VECTOR CLASSIFICATION**
"""

import pandas as pd
import matplotlib.pyplot as plt
import time
from sklearn.svm import SVC
from sklearn.metrics import (accuracy_score, roc_auc_score, f1_score, precision_score, recall_score, ConfusionMatrixDisplay, roc_curve)

# Ensure the SVM model is defined and fitted
# These variables (X_train_transformed_local, y_train, X_test_transformed_local, y_test)
# are assumed to be available from previous execution in the notebook.
svm_model = SVC(class_weight='balanced', probability=True)
start = time.time()
svm_model.fit(X_train_transformed_local, y_train)
stop = time.time()

fit_time = str(round(stop - start, 2)) + ' seconds'

y_pred_svm = svm_model.predict(X_test_transformed_local)
y_proba_svm = svm_model.predict_proba(X_test_transformed_local)

# The results_df currently in the kernel might only have KNN data.
# This code will add a new row for SVM, extending the existing DataFrame.
# Ensure 'Fit Time' column exists as it is used here.
if 'Fit Time' not in results_df.columns:
    results_df['Fit Time'] = None

results_df.loc['SVM', 'Fit Time'] = fit_time
results_df.loc['SVM', 'Accuracy'] = accuracy_score(y_test, y_pred_svm)
results_df.loc['SVM', 'ROC_AUC'] = roc_auc_score((y_test == 0).astype(int), y_proba_svm[:, 0])
results_df.loc['SVM', 'F1'] = f1_score(y_test, y_pred_svm, pos_label=0, zero_division=0)
results_df.loc['SVM', 'Precision'] = precision_score(y_test, y_pred_svm, pos_label=0, zero_division=0)
results_df.loc['SVM', 'Recall'] = recall_score(y_test, y_pred_svm, pos_label=0, zero_division=0)

print(results_df.loc['SVM'])

# Confusion Matrix
ConfusionMatrixDisplay.from_predictions(y_test, y_pred_svm, display_labels=svm_model.classes_, cmap='Blues')
plt.title('Confusion Matrix - SVM')
plt.show()

# ROC Curve for class 0 (MM)
# y_true needs to be binary with positive class as 1 for roc_curve
# y_score needs to be probability of positive class
fpr, tpr, thresholds = roc_curve(
    (y_test == 0).astype(int),  # y_true: where original class 0 (MM) is now 1
    y_proba_svm[:, 0],          # y_score: probability of original class 0 (MM)
    pos_label=1                 # Explicitly state that the positive label in (y_test == 0).astype(int) is 1
)
plt.figure(figsize=(10, 6))
plt.plot(fpr, tpr, label=f"SVM(AUC={results_df.loc['SVM', 'ROC_AUC']:.2f})")
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - SVM (Class 0 as Positive)')
plt.legend()
plt.show()

"""The model has excellent ability to distinguish MM/high risk patients from healthy/non-high risk patients. AUC values  above 0.90 are generally considered clinically strong, highly discriminative.The ROC curve bends strongly toward the upper-left corner, which indicates high sensitivity and relatively low false positive rate.

Precision is 95%, of all patients predicted as MM/high risk, 95% truly were MM/high risk. There were very few false positive predictions. The model is highly reliable when it predicts disease/high risk. This reduces unnecessary follow up testing and false alarms.

The SVM model demonstrates excellent discrimination performance with an ROC_AUC of 0.90 and very high precision (95%), indicating that predicted MM/high-risk classifications are very reliable. The confusion matrix shows that the model correctly identified most disease patients while producing very few false positives. Although recall was lower at 72%, suggesting some MM/high-risk patients were missed, the overall F1-score of 0.82 indicates a strong balance between sensitivity and precision. Overall, the SVM appears clinically promising for identifying high-risk multiple myeloma patients.

**DECISION TREE CLASSIFIER**
"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (accuracy_score, roc_auc_score, f1_score, precision_score, recall_score, ConfusionMatrixDisplay, roc_curve)
import pandas as pd
import matplotlib.pyplot as plt
import time

results_df= pd.DataFrame(columns=('Accuracy','ROC_AUC','F1','Precision','Recall'))
dt_model = DecisionTreeClassifier(class_weight='balanced', random_state=42)
dt_model.fit(X_train_transformed_local, y_train)


y_pred= dt_model.predict(X_test_transformed_local)
y_proba= dt_model.predict_proba(X_test_transformed_local)

y_proba_transform= y_proba[:,0]

results_df.loc['Decision Tree', 'Accuracy'] = accuracy_score(y_test, y_pred)

results_df.loc['Decision Tree', 'ROC_AUC'] = roc_auc_score(
    (y_test==0).astype(int),
     y_proba_transform)

results_df.loc['Decision Tree', 'F1'] = f1_score(y_test, y_pred, pos_label=0)
results_df.loc['Decision Tree', 'Precision'] = precision_score(y_test, y_pred, pos_label=0)
results_df.loc['Decision Tree', 'Recall'] = recall_score(y_test, y_pred,pos_label=0)

print(results_df.loc['Decision Tree'])

ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred,
    display_labels=['Transformed to MM', 'Did not transform'],
    cmap='Blues'
)

plt.title('Confusion Matrix- Decision Tree')
plt.show()

fpr,tpr,thresholds = roc_curve(
    (y_test==0).astype(int),
    y_proba_transform)

plt.figure(figsize=(10,6))
plt.plot(fpr, tpr, label= f"Decision Tree(AUC={results_df.loc['Decision Tree', 'ROC_AUC']:.2f})")
plt.plot([0,1],[0,1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve- Decision Tree')
plt.legend()
plt.show()

"""The decision tree has good discrimination ability. However, compared with SVM the curve is less smooth, less close to the upper-left corner. This suggest weaker discrimination than SVM.

The model detected about 82% of all true MM/high-risk patients. This is clinically meaningful because relatively few transformed patients were missed.
F1= 0.86, the model achieved a strong precision, strong recall and good balance overrall.

The Decision Tree model demonstrated strong predictive performance for MM transformation. The confusion matrix showed that most transformend MM patients were correctly identified while maintaining relatively few false positive predictions. The ROC curve produced an AUC of 0.80, indicating good discrimination between transformed and non-transformed patients. Precision remained high at 90%, meaning predictions of MM transformation were highly reliable, while recall of 82% showed the model successfully detected most high-risk patients. Overall, the Decision Tree provided a strong balance between sensitivity and precision and may offer clinically interpretable decision rules for MM progression prediction.

**RANDOM FOREST CLASSIFIER**

Some of the strenghts of Random Forest are highest ROC_AUC, highest overall accuracy, very strong class discrimination, and low false negatives.
"""

import pandas as pd
import matplotlib.pyplot as plt
import time

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, roc_auc_score, f1_score, precision_score, recall_score, ConfusionMatrixDisplay)

# Assuming results_df is initialized earlier in the notebook, if not, it should be re-initialized.
# Based on the previous execution, results_df should already be a DataFrame.
# If this is the first model in a fresh run, then results_df needs to be defined.
# For now, assuming results_df is already defined from a previous cell.
# If results_df is not defined before this cell, uncomment the next line:
# results_df = pd.DataFrame(columns=('Accuracy', 'ROC_AUC', 'F1', 'Precision', 'Recall'))

rf_model= RandomForestClassifier(class_weight='balanced',n_estimators=100, random_state=42)
rf_model.fit(X_train_transformed_local, y_train)

y_pred= rf_model.predict(X_test_transformed_local)
y_proba= rf_model.predict_proba(X_test_transformed_local)[:,1]

# Ensure results_df is properly initialized to avoid potential KeyError if this is the first model run in a fresh kernel
if 'random forest' not in results_df.index:
    results_df.loc['random forest', :] = None # Initialize the row if it doesn't exist

results_df.loc['random forest', 'Accuracy'] = accuracy_score(y_test,y_pred)
results_df.loc['random forest', 'ROC_AUC'] = roc_auc_score(y_test, y_proba)
results_df.loc['random forest', 'F1'] = f1_score(y_test,y_pred)
results_df.loc['random forest', 'Precision'] = precision_score(y_test,y_pred, zero_division=0)
results_df.loc['random forest', 'Recall'] = recall_score(y_test,y_pred)

print(results_df.loc['random forest'])

fpr,tpr,thresholds = roc_curve(y_test, y_proba)

plt.figure(figsize=(8,6)) # Corrected: figsize should be a tuple

plt.plot(fpr,tpr, label= f"Random Forest (AUC = {results_df.loc['random forest', 'ROC_AUC']:.2f})")
plt.plot([0,1],[0,1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve: Random Forest')
plt.legend(loc='lower right')
plt.show()

ConfusionMatrixDisplay.from_predictions(y_test, y_pred, display_labels=rf_model.classes_, cmap='Blues')
plt.title('Confusion Matrix: Random Forest')
plt.show()

print(results_df)

"""The Random Forest model demonstrated excellent discrimination performance with an ROC_AUC of 0.92 and the highest overall accuracy among the evaluated models. The ROC curve showed strong separation between MM/high-risk and non-transforming patients, indicating that the model effectively captures complex clinical patterns associated with disease progression. The confusion matrix demonstrated that most MM patients were correctly identified, with relatively few false negatives and false positives. Although recall was somewhat lower than the Decision Tree model, the Random Forest achieved excellent overall predictive performance and appears highly promising for MM progression prediction.

**EXTREME GRADIENT BOOSTING**

Extreme Gradient Boosting model effectively captures complex nonlinear clinical relationships involving: M spike, K/L ratio, TP 53, cytogenetics, and demographic variables.
"""

import pandas as pd
import matplotlib.pyplot as plt
import time

from xgboost import XGBClassifier
from sklearn.metrics import (accuracy_score, roc_auc_score, f1_score,precision_score, recall_score, ConfusionMatrixDisplay, roc_curve)

negative_count= (y_train==0).sum()
positive_count = (y_train==1).sum()

scale_pos_weight = negative_count / positive_count

results_df= pd.DataFrame(columns=('Accuracy','ROC_AUC','F1','Precision','Recall'))

xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.1,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric= 'logloss'
)

xgb_model.fit(X_train_transformed_local, y_train)

y_pred= xgb_model.predict(X_test_transformed_local)
y_proba= xgb_model.predict_proba(X_test_transformed_local)[:,1]

results_df.loc['XGBoost', 'Accuracy'] = accuracy_score(y_test, y_pred)
results_df.loc['XGBoost', 'ROC_AUC'] = roc_auc_score(y_test, y_proba)
results_df.loc['XGBoost', 'F1'] = f1_score(y_test, y_pred)
results_df.loc['XGBoost', 'Precision'] = precision_score(y_test, y_pred, zero_division=0)
results_df.loc['XGBoost', 'Recall'] = recall_score(y_test, y_pred)

print(results_df.loc['XGBoost'])

fpr,tpr,thresholds = roc_curve(y_test, y_proba)
plt.figure(figsize=(10,6))
plt.plot(fpr, tpr,label= f"XGBoost(AUC={results_df.loc['XGBoost', 'ROC_AUC']:.2f})")

plt.plot([0,1],[0,1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve- XGBoost')
plt.legend(loc='lower right')
plt.show()

print(results_df.loc['XGBoost'])

ConfusionMatrixDisplay.from_predictions(y_test, y_pred, display_labels=xgb_model.classes_, cmap='Blues')
plt.title('Confusion Matrix- XGBoost')
plt.show()

print(results_df)

"""The XGBoost model demonstrated excellent discrimination performance with an ROC_AUC of 0.91, indicating strong ability to separate MM/high-risk and non-transforming patients. The ROC curve showed clear improvement over random classification and strong sensitivity across multiple thresholds. The confusion
matrix demonstrated that the model correctly identified most MM/high-risk patients while maintaining relatively  few false positive predictions. Recall remained high at 83%, suggesting the model is effective for detecting clinically important MM transformation cases. Overall, XGBoost appears highly promising for MM progression prediction, particularly when identifying high risk patients is a clinical priority.

**IMPROVING THE MODEL**-
**Logistic Regression & GridSearch**

GridSearch improves the Logistic Regression model because it automatically finds the best hyperparameters instead of using default settings.
"""

import time
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    classification_report,
    accuracy_score,
    roc_auc_score, f1_score, precision_score, recall_score, ConfusionMatrixDisplay, roc_curve
)
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

# Define the pipeline for Logistic Regression
lgr_pipe = Pipeline(steps=[
    ('preprocessor', column_transformer),
    ('classifier', LogisticRegression(random_state=42, solver='liblinear'))
])

# Define the parameters for GridSearchCV
lgr_params = {
    'classifier__C': [0.001, 0.01, 0.1, 1, 10, 100],
    'classifier__penalty': ['l1', 'l2'],
    'classifier__class_weight': [None, 'balanced']
}

lgr_grid= GridSearchCV(
    lgr_pipe,
    param_grid=lgr_params,
    cv=5,
    scoring='roc_auc'
)

start= time.time()
lgr_grid.fit(X_train, y_train)
stop= time.time()

fit_time= str(round(stop-start,2)) + ' seconds'

print(f"Best Parameters: {lgr_grid.best_params_}")
print(f"Best Score: {lgr_grid.best_score_}")

#Predictions
y_pred= lgr_grid.predict(X_test)
y_probs= lgr_grid.predict_proba(X_test)[:,1]

print(classification_report(y_test, y_pred, zero_division=0))

lgr_roc_score= roc_auc_score(y_test, y_probs)
print(f"ROC AUC Score for Logistic Regression= {lgr_roc_score:.3f}")

fpr,tpr,thresholds = roc_curve(y_test, y_probs)

plt.figure(figsize=(10,6))
plt.plot(fpr, tpr, label= f"Logistic Regression(AUC={lgr_roc_score:.2f})")
plt.plot([0,1],[0,1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve- Logistic Regression')
plt.legend()
plt.show()

ConfusionMatrixDisplay.from_predictions(y_test, y_pred, cmap='Blues')
plt.title('Confusion Matrix- Logistic Regression')
plt.show()

# Ensure results_df is properly initialized if not already done in the current scope
if 'GridSearch Logistic Regression' not in results_df.index:
    results_df.loc['GridSearch Logistic Regression', :] = None

results_df.loc['GridSearch Logistic Regression', 'Fit Time'] = fit_time
results_df.loc['GridSearch Logistic Regression', 'Accuracy'] = accuracy_score(y_test, y_pred)
results_df.loc['GridSearch Logistic Regression', 'ROC_AUC'] = roc_auc_score(y_test, y_pred)
results_df.loc['GridSearch Logistic Regression', 'F1'] = f1_score(y_test, y_pred)
results_df.loc['GridSearch Logistic Regression', 'Precision'] = precision_score(y_test, y_pred,zero_division=0)
results_df.loc['GridSearch Logistic Regression', 'Recall'] = recall_score(y_test, y_pred)

print(results_df.loc['GridSearch Logistic Regression'])

"""The model consistently achieved strong discrimination ability, across multiple validation folds. The model generalizes reasonably well, performance is stable, less likely due to random chance.

The GridSearch Logistic Regression Model demonstrated very good discrimination performance with an ROC_AUC of 0.87, indicating strong ability to distinguish MM/high-risk patients from healthy patients. The ROC curve remained well above the random classification line, showing that the model performs substantially better than chance. The confusion matrix demonstrated that most MM/high-risk patients were correctly identified while maintaining a very low false positive rate. Although some transformed MM patients were missed, the model achieved a strong balance between sensitivity and specificity, making it clinically useful for MM progression prediction.

**KNeighbors & GridSearch**

KNeighborsClassifier & GridSearchCV is important because KNN performance depends heavily on choosing the correct hyperparameters. Without tunning KNN may overfit, underfit, perform inconsistently, and make poor clinical predictions. Closer patients influence predictions more strongly. This is often clinically meaninful because patients with similar biomarkers, similar cytogenetics and similar TP53 profiles may be more biologically relevant. GridSearch determines which approach works better.
"""

import time
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    classification_report,
    accuracy_score,
    roc_auc_score,f1_score, precision_score, recall_score, ConfusionMatrixDisplay, roc_curve
)

knn_params= {
    'knn__n_neighbors': list (range(1,10)),
    'knn__p': [1,2,3],
    'knn__weights': ['uniform', 'distance']
}
knn_pipe= Pipeline([
    ('columns', column_transformer),
    ('knn', KNeighborsClassifier())
])

knn_grid= GridSearchCV(
    knn_pipe,
    param_grid=knn_params,
    scoring='roc_auc',
    cv=5
)
start= time.time()
knn_grid.fit(X_train, y_train)
stop= time.time()

fit_time= str(round(stop-start,2)) + ' seconds'

print(f"Best Parameters: {knn_grid.best_params_}")
print(f"Best Score: {knn_grid.best_score_}")

y_pred= knn_grid.predict(X_test)
y_probs= knn_grid.predict_proba(X_test)[:,1]

print(classification_report(y_test, y_pred, zero_division=0))

knn_roc_score= roc_auc_score(y_test, y_probs)
print(f"ROC AUC Score for KNN= {knn_roc_score}")

fpr,tpr,thresholds = roc_curve(y_test, y_probs)
print('False Positive Rates:', fpr[:5])
print('True Positive Rates:', tpr[:5])

plt.figure(figsize=(10,6))
plt.plot(fpr, tpr,'--o', label= f"KNN(AUC={knn_roc_score:.2f})")
plt.plot([0,1],[0,1], 'k--', label='Baseline')
plt.legend()
plt.title('ROC Curve- KNN')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.show()

ConfusionMatrixDisplay.from_predictions(y_test, y_pred, cmap='Blues')
plt.title('Confusion Matrix- KNN')
plt.show()

results_df.loc['GridSearch KNN', 'Fit Time'] = fit_time
results_df.loc['GridSearch KNN', 'Accuracy'] = accuracy_score(y_test, y_pred)
results_df.loc['GridSearch KNN', 'ROC_AUC'] = roc_auc_score(y_test, y_pred)
results_df.loc['GridSearch KNN', 'F1'] = f1_score(y_test, y_pred)
results_df.loc['GridSearch KNN', 'Precision'] = precision_score(y_test, y_pred,zero_division=0)
results_df.loc['GridSearch KNN', 'Recall'] = recall_score(y_test, y_pred)

print(results_df.loc['GridSearch KNN'])

"""The tuned KNN model demonstrated excellent overall predictive performance for MM/high-risk transformation. The GridSearch optimization identified an optimal neighborhood structure that produced highly balanced classification performance. The confusion matrix showed that most MM/high-risk patients were correctly identified while maintaining relatively few false positive predictions. The ROC curve demonstrated strong discrimination ability with an ROC_AUC of 0.87. Importantly, the model achieved both high precision and high recall (88-89%), indicating that the model was highly effective at detecting MM transformation while minimizing false alarms. Overall, the optimized KNN model appears highly clinically promising for MM progression prediction.

**SVM & GRIDSEARCH**

SVM focuses on the support vectors, which can help generalization and reduce overfitting. The advantages of using together SVM and GridSearchCV is to optimize complex classification boundaries, improve predictive accuracy, tune hyperparameters systematically, and build stronger models for clinical prediction tasks.
"""

import time
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.metrics import (
    classification_report, # Corrected: 'Classification_report' to 'classification_report'
    accuracy_score,
    roc_auc_score,
    f1_score,precision_score, recall_score, ConfusionMatrixDisplay, roc_curve
)

# Define the SVM pipeline
svm_pipe = Pipeline(steps=[
    ('preprocessor', column_transformer),
    ('svc', SVC(random_state=42, probability=True)) # Added probability=True for roc_auc_score and random_state
])

# Corrected svm_params dictionary
svm_params= {
    'svc__kernel':['poly','rbf', 'sigmoid'], # Corrected: added closing quote to 'sigmoid'
    'svc__degree': [1,2,3],
    'svc__gamma':[ 1,0.1,0.01,0.001],
    'svc__C': [0.1,1,10,100] # Corrected: 'svc,C' to 'svc__C'
}

svc_grid= GridSearchCV(
    svm_pipe,
    param_grid=svm_params,
    cv=5,
    scoring='roc_auc'
)
start=time.time()
svc_grid.fit(X_train, y_train) # Corrected: Use X_train, y_train for fitting
stop= time.time()

fit_time= str(round(stop-start,2)) + ' seconds'

print(f"Best Parameters for SVC: {svc_grid.best_params_}")
print(f"Best Score for SVC: {svc_grid.best_score_}")

y_pred_svm= svc_grid.predict(X_test) # Corrected: Use X_test for prediction
y_proba_svm= svc_grid.predict_proba(X_test)[:,1] # Corrected: Use X_test for proba prediction

print(classification_report(y_test, y_pred_svm)) # Corrected: Use y_test

svc_roc_score= roc_auc_score(y_test, y_proba_svm) # Corrected: Use y_test
print(f"ROC AUC Score for SVM= {svc_roc_score}")

#ROC curve

fpr,tpr,thresholds = roc_curve(y_test, y_proba_svm) # Corrected: Use y_test

print('False Positive Rates:', fpr[:5])
print('True Positive Rates:', tpr[:5])

plt.figure(figsize=(10,6))
plt.plot(fpr, tpr, '--o',label='SVC ROC Curve')
plt.plot([0,1],[0,1], 'k--', label='Baseline')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve- SVM')
plt.legend()
plt.show()

#Confusion matrix

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_svm, cmap='Blues') # Corrected: Use y_test
plt.title('Confusion Matrix- SVM')
plt.show()

# Ensure results_df is properly initialized if not already done in the current scope
if 'GridSearch SVM' not in results_df.index:
    results_df.loc['GridSearch SVM', :] = None

results_df.loc['GridSearch SVM', 'Fit Time'] = fit_time
results_df.loc['GridSearch SVM', 'Accuracy'] = accuracy_score(y_test, y_pred_svm) # Corrected: Use y_test
results_df.loc['GridSearch SVM', 'ROC_AUC'] = roc_auc_score(y_test, y_proba_svm) # Corrected: Assign actual score
results_df.loc['GridSearch SVM', 'F1'] = f1_score(y_test, y_pred_svm) # Corrected: Use y_test and y_pred_svm
results_df.loc['GridSearch SVM', 'Precision'] = precision_score(y_test, y_pred_svm,zero_division=0) # Corrected: Use y_test
results_df.loc['GridSearch SVM', 'Recall'] = recall_score(y_test,y_pred_svm) # Corrected: Use y_test and y_pred_svm


print(results_df.loc['GridSearch SVM']) # Corrected: 'SVC' to 'GridSearch SVM'

"""The Classification report shows strong performance for class 0 (precision 0.93, recall 0.91, f1-score 0.92) and good performance for class 1 (precision 0.79, recall 0.83, f1-score 0.81). The ROC curve and Confusion Matrix plots have also been generated to visualize these results.

The model demonstrated strong predictive performance with: high overall accuracy(89%), excellent ROC_AUC (0.90), strong recall for the positive class, and  low false negative rates. The RBF kernel successfully captured nonlinear relationships in the dataset, while GridSearchCV helped identify hyperparameters that balanced sensitivity and specificity effectively. Clinically, this model appears promising for identifyng patients at higher risk while minimizing missed cases and maintaining relatively few false alarms.

**DECISION TREES &** **GRIDSEARCH**

Decision Trees can model complex relationships between variables without requiring linear assumptions. Using Decision Trees with GridSearchCV provides interpretable models, optimized predictive performance, reduced overfitting, and improved clinical decision support.
"""

import time

from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import (
    classification_report,
    accuracy_score,
    roc_auc_score,
    f1_score, precision_score, recall_score, ConfusionMatrixDisplay, roc_curve
)

dtree_params ={
    'dtree__max_depth': list(range(1,11,2)),
    'dtree__min_samples_split': list(range(2,11)),
    'dtree__criterion': ['gini','entropy'],
    'dtree__class_weight': [None, 'balanced'], # Added comma here
    'dtree__min_samples_leaf': list(range(2,21,2))
}

dtree_pipe= Pipeline([
    ('columns', column_transformer),
    ('dtree', DecisionTreeClassifier(
        class_weight= 'balanced',
        random_state=42 # Added comma here
    ))
])

dtree_grid= GridSearchCV(
    dtree_pipe,
    param_grid=dtree_params,
    scoring='roc_auc',
    cv=5)

start= time.time()
dtree_grid.fit(X_train, y_train)
stop= time.time()

fit_time= str(round(stop-start,2)) + ' seconds'

print("Best Parameters:", dtree_grid.best_params_)
print("Best CV ROC_AUC Score:", dtree_grid.best_score_)
print("Fit Time", fit_time)

#Predictions
y_pred = dtree_grid.predict(X_test)
y_pred_probs = dtree_grid.predict_proba(X_test)[:,1]

print(classification_report(y_test, y_pred))

dtree_roc_score = roc_auc_score(y_test, y_pred_probs)

print(f"ROC AUC Score for Decision Tree: {dtree_roc_score}")

#ROC curve

fpr,tpr,thresholds = roc_curve(y_test, y_pred_probs)
plt.figure(figsize=(10,6))
plt.plot(fpr, tpr, '--o',label='Decision Tree ROC Curve')
plt.plot([0,1],[0,1], 'k--', label='Baseline')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve- Decision Tree')
plt.legend()
plt.show()

# Confusion matrix

ConfusionMatrixDisplay.from_predictions(y_test, y_pred, cmap='Blues')
plt.title('Confusion Matrix- Decision Tree')
plt.show()

#save results

results_df.loc['GridSearch Decision Tree', 'Fit Time'] = fit_time
results_df.loc['GridSearch Decision Tree', 'Accuracy'] = accuracy_score(y_test, y_pred)
results_df.loc['GridSearch Decision Tree', 'ROC_AUC'] = dtree_roc_score
results_df.loc['GridSearch Decision Tree', 'F1'] = f1_score(y_test, y_pred)
results_df.loc['GridSearch Decision Tree', 'Precision'] = precision_score(y_test, y_pred, zero_division=0) # Changed zero_division=2 to zero_division=0
results_df.loc['GridSearch Decision Tree', 'Recall'] = recall_score(y_test, y_pred)

print(results_df.loc['GridSearch Decision Tree'])

"""The Decision Tree model demonstrated moderate predictive performance and successfully identified many patients correctly. The model showed acceptable sensitivity and specificity, but produced more false positives and false negatives than the SVM model.
The ROC curve confirms that the Decision Tree has useful discrimination ability, although it is less effective at separating high-risk and low-risk patients compared with SVM. Clinically, the higher number of missed positive cases may limit its reliability for disease progression prediction where early identification is critical. Despite these limitations, Decision Trees remain valuable because they are interpretable, decision rules are easy to explain, and clinicians can visualize feature splits and variable importance. For this dataset, SVM appears to provide superior predictive performance and better overall generalization.

"""



"""**RANDOM FOREST AND GRIDSEARCH**

Using Random Forest with GridSearchCV provides strong predictive performance, reduced overfitting, robust handling of complex data, optimized hyperparameters, and reliable clinical prediction models.
"""

import time
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    accuracy_score,
    roc_auc_score,
    f1_score,
    precision_score,
    recall_score,
    ConfusionMatrixDisplay,
    roc_curve
)

# Using the globally defined X_train, y_train, X_test, y_test

#Parameters

rf_params={
    'rf__n_estimators': [100,200,300],
    'rf__max_depth': [None, 3,5,10],
    'rf__min_samples_split': [2,5,10],
    'rf__min_samples_leaf': [1,2,4],
    'rf__max_features': ['sqrt', 'log2'] # Corrected parameter name
}
#Pipeline

rf_pipe= Pipeline([
    ('columns', column_transformer),
    ('rf', RandomForestClassifier(
    class_weight='balanced',
    random_state=42))
])
# Grid Search

rf_grid= GridSearchCV(
    rf_pipe,
    param_grid=rf_params,
    cv=5,
    scoring='roc_auc' # Added scoring for GridSearchCV
)

#Fit model

start= time.time()
rf_grid.fit(X_train, y_train) # Using global X_train, y_train
stop= time.time()

fit_time= str(round(stop-start,2)) + ' seconds'

print(f"Best Parameters for Random Forest: {rf_grid.best_params_}")
print(f"Best CV ROC_AUC Score: {rf_grid.best_score_}")

#Predict

y_pred= rf_grid.predict(X_test) # Using global X_test
y_pred_probs= rf_grid.predict_proba(X_test)[:,1] # Using global X_test

#Metrics
print(classification_report(y_test, y_pred)) # Using global y_test

rf_roc_score= roc_auc_score(y_test, y_pred_probs) # Using global y_test
print(f"ROC AUC Score for Random Forest= {rf_roc_score}")

#ROC curve

fpr,tpr,thresholds = roc_curve(y_test, y_pred_probs) # Using global y_test

plt.figure(figsize=(10,6))
plt.plot(fpr, tpr, '--o',label='Random Forest ROC Curve')
plt.plot([0,1],[0,1], 'k--', label='Baseline')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve- Random Forest')
plt.legend()
plt.show()

#Confusion matrix

ConfusionMatrixDisplay.from_predictions(y_test, y_pred, cmap='Blues') # Using global y_test

plt.title ('Confusion Matrix- Random Forest')
plt.show()

# Ensure results_df is properly initialized if not already done in the current scope
if 'GridSearch Random Forest' not in results_df.index:
    results_df.loc['GridSearch Random Forest', :] = None

results_df.loc['GridSearch Random Forest', 'Fit Time'] = fit_time
results_df.loc['GridSearch Random Forest', 'Accuracy'] = accuracy_score(y_test, y_pred)
results_df.loc['GridSearch Random Forest', 'ROC_AUC'] = rf_roc_score
results_df.loc['GridSearch Random Forest', 'F1'] = f1_score(y_test, y_pred, zero_division=0)
results_df.loc['GridSearch Random Forest', 'Precision'] = precision_score(y_test, y_pred,zero_division=0)
results_df.loc['GridSearch Random Forest', 'Recall'] = recall_score(y_test, y_pred)

print(results_df.loc['GridSearch Random Forest'])

"""The optimized Random Forest model demonstrated excellent predictive performance  with strong ROC-AUC, high overall accuracy, and balanced sensitivity and specificity. GridSearchCV successfully identified parameters that reduced overfitting while maintaining strong generalization. The confusion matrix and ROC curve show that the model effectively distinguishes between positive and negative patients with relatively few false negatives and false positives. Compared with a single Decision Tree, the Random Forest provided substantially improved stability and predictive power. Clinically, this model appears highly promising for disease progression prediction and risk stratification in patients.

**EXTREME GRADIENT BOOSTING & GRIDSEARCH **

Using XGBoost with GridSearchCV provides highly optimized predictive models, strong discrimination ability, improved robustness, excellent handling of complex clinical data, and reduced overfitting.
"""

import time
import numpy as np
import matplotlib.pyplot as plt

from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    classification_report,
    accuracy_score,
    roc_auc_score, f1_score, precision_score, recall_score, ConfusionMatrixDisplay, roc_curve
)
#Calculate class balance for XGBoost
negative_count= (y_train == 0).sum()
positive_count= (y_train == 1).sum()

scale_pos_weight= negative_count / positive_count

#XGBoost parameter grid

xgb_params= {
    'xgb__n_estimators': [100,200],
    'xgb__max_depth': [3,5,7],
    'xgb__learning_rate': [0.01,0.1],
    'xgb__subsample': [0.8,1.0],
    'xgb__colsample_bytree': [0.8,1.0],

}

#Pipeline

xgb_pipe= Pipeline([
    ('columns', column_transformer),
    ('xgb', XGBClassifier(
        scale_pos_weight= scale_pos_weight,
        random_state=42,
        eval_metric ='logloss'
    ))
])

#GridSearch

xgb_grid= GridSearchCV(
    xgb_pipe,
    param_grid=xgb_params,
    scoring='roc_auc',
    cv=5
)

# Fit model and time it

start= time.time()
xgb_grid.fit(X_train, y_train)
stop=time.time()

fit_time= str(round(stop-start,2)) + ' seconds'

print(f"Best Parameters for XGBoost: {xgb_grid.best_params_}")
print(f"Best CV ROC_AUC Score: {xgb_grid.best_score_}")
print(f"Fit Time: {fit_time}")

#Predictions

y_pred = xgb_grid.predict(X_test)
y_pred_probs = xgb_grid.predict_proba(X_test)[:,1]

#Classification report

print(classification_report(y_test, y_pred))

#ROC_AUC
xgb_roc_score = roc_auc_score(y_test, y_pred_probs)
fpr,tpr,thresholds = roc_curve(y_test, y_pred_probs)

plt.figure(figsize=(10,6))
plt.plot(fpr, tpr, '--o',label='XGBoost ROC Curve')
plt.plot([0,1],[0,1], 'k--', label='Baseline')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve- XGBoost')
plt.legend()
plt.show()

#Confusion matrix

ConfusionMatrixDisplay.from_predictions(y_test, y_pred, cmap='Blues')
plt.title('Confusion Matrix- XGBoost')
plt.show()

#save results

results_df.loc['GridSearch XGBoost', 'Fit Time'] = fit_time
results_df.loc['GridSearch XGBoost', 'Accuracy'] = accuracy_score(y_test, y_pred)
results_df.loc['GridSearch XGBoost', 'ROC_AUC'] = xgb_roc_score
results_df.loc['GridSearch XGBoost', 'F1'] = f1_score(y_test, y_pred)
results_df.loc['GridSearch XGBoost', 'Precision'] = precision_score(y_test, y_pred,zero_division=0)
results_df.loc['GridSearch XGBoost', 'Recall'] = recall_score(y_test, y_pred)

print(results_df.loc['GridSearch XGBoost'])

"""The XGBoost model demonstrated excellent discrimination ability during cross validation and effectively capture complex nonlinear relationships within the dataset. Hyperparameter optimization through GridSearchCV produced a robust boosting model with strong sensitivity for identifying positive/high-risk patients.
Although the final test accuracy was lower than the SVM and Random Forest models, XGBoost maintained good recall for the positive class, suggesting strong potential for detecting disease progression. However, the lower precision indicates a higher false positive rate, which may lead to additional follow-up evaluations.
The ROC curve confirmed that the model effectively separates classes and maintains predictive power well above random classification.
The confusion matrix showed that the model succesfully detected many positive patients while maintaining relatively few false negatives. However, this performance came at the expense of increased false positives and reduced specificity compared with SVM and Random Forest.
Clinically, XGBoost maybe particularly useful in settings where maximizing detection of high-risk patients is prioritized over minimizing false alarms. Threshold optimization may further improve its balance between sensitivity and specificity.   
"""



"""**MODEL COMPARISON**"""

results_df

"""Choose a decision threshold based on my goal (catching progression) instead of blindly using 0.5"""

y_pred_proba = xgb_grid.predict_proba(X_test)[:,1]

"""This code helps identify the best probability threshold for the  prediction model by evaluating precision, recall and F1-score across multiple cutoff values.
Lower thresholds generally increase recall(detecting more high-risk patients) but may reduce precision by increasing false positives. Higher thresholds improve precision but may missed positive patients, lowering recall.
In clinical prediction tasks such as disease progression modeling, threshold tuning is especially important because the optimal balance depends on whether minimizing false negatives or false positives is the primary clinical goal.
"""

import numpy as np
import pandas as pd

from sklearn.metrics import precision_score, recall_score, f1_score

# Initialize storage

results = []

#Define thresholds to test

thresholds= np.arange(0.1,0.9,0.05)

# Loop through to test

for t in thresholds:
    y_pred_t= (y_pred_probs>=t).astype(int)

    precision= precision_score(y_test, y_pred_t, zero_division=0)
    recall= recall_score(y_test, y_pred_t)
    f1= f1_score(y_test, y_pred_t)
    results.append((t, precision, recall, f1))

#convert to DataFrame

threshold_df= pd.DataFrame(results, columns=['Threshold', 'Precision', 'Recall', 'F1'])

print(threshold_df)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.plot(threshold_df['Threshold'], threshold_df['Precision'], label='Precision')
plt.plot(threshold_df['Threshold'], threshold_df['Recall'], label='Recall')
plt.plot(threshold_df['Threshold'], threshold_df['F1'], label='F1')
plt.xlabel('Threshold')
plt.ylabel('Score')
plt.title('Precision, Recall, and F1 for Different Thresholds')
plt.legend()
plt.show()

"""The graph demonstrates a clear trade-off between sensitivity(recall) and precision as the classification threshold changes. Lower thresholds maximize detection of positive/high-risk patients but increase false positives, while higher thresholds improve precision at the cost of missing more true positive cases.
The F1-score suggests that thresholds around 0.25-0.35 may provide the best balance between sensitivity and precision for this dataset. Clinically, the optimal threshold depends on the goal of the prediction model. If early disease detection is the priority, a lower threshold with higher recall may be preferable. If minimizing unnecessary interventions is more important a higher threshold with improved precision may be selected.

In order not to miss patients who progressed, we should pick a threshold where the recall is high (e.g.,>= 0.85-0.90)
"""

best_threshold = threshold_df.loc[threshold_df['Recall']>= 0.85].iloc[0] ['Threshold']
print(best_threshold)

y_pred_final= (y_pred_probs>= best_threshold).astype(int)

from sklearn.metrics import classification_report,ConfusionMatrixDisplay

print (classification_report(y_test, y_pred_final))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_final, cmap='Blues')
plt.title(f'Confusion Matrix (Threshold={best_threshold})')
plt.show()

"""The results showed that when we lower the classification threshold to 0.1. The model becomes much more sensitive to detecting positive/high-risk patients, but this comes at the cost of many more false positives and lower overall accuracy.

Compare all models at the same recall level (eg.,0.85) and see which one gives best precision.

**Collect Probabilities from all models**
"""

probs={
    'LogReg': lgr_grid.predict_proba(X_test)[:,1],
    'KNN': knn_grid.predict_proba(X_test)[:,1],
    'SVM': svc_grid.predict_proba(X_test)[:,1],
    'Decision Tree': dtree_grid.predict_proba(X_test)[:,1],
    'Random Forest': rf_grid.predict_proba(X_test)[:,1],
    'XGBoost': xgb_grid.predict_proba(X_test)[:,1]
}

"""**Function to find best threshold at target recall**"""

import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score
def find_best_threshold(y_true, y_probs, target_recall=0.85):
  thresholds= np.linspace(0.01,0.99,100)
  best=None
  for t in thresholds:
    y_pred_t= (y_probs>=t).astype(int)
    recall= recall_score(y_true, y_pred_t)
    precision = precision_score(y_true, y_pred_t, zero_division=0)
    if recall >= target_recall:
       if best is None or precision > best['precision']:
        best= {
            'threshold':t,
            'precision': precision,
            'recall': recall}

  return best

"""**Run Comparison**"""

results= []

for name, y_probs in probs.items():
     y_true = y_test # Use y_test for all models for consistency

     best = find_best_threshold(y_true, y_probs, target_recall=0.85)
     if best is not None:
       results.append({
           'Model': name,
          'Threshold': round(best['threshold'], 2),
           'Recall': round(best['recall'], 2),
           'Precision': round(best['precision'], 3)
       })

import pandas as pd
comparison_df= pd.DataFrame(results).sort_values(by='Precision', ascending=False)
print(comparison_df)

"""This means  that at the same recall(0.85): XGBoost gives highest precision--> best model. It flags fewer false positives for same safety level."""

import matplotlib.pyplot as plt

plt.barh(comparison_df['Model'], comparison_df['Precision'])
plt.xlabel('Precision (at Recall = 0.85)')
plt.title('Model Comparison at Fixed  Recall')
plt.gca().invert_yaxis()
plt.show()

"""This graph demonstrates how different machine learning models perform when sensitivity is prioritized. At a fixed recall of approximately 0.85,XGBoost achieved the highest precision, indicating the best balance between detecting high-risk patients and minimizing false positives.
Random Forest and KNN also demonstrated strong performance, while SVM showed moderate reduction in precision when adjusted for higher sensitivity. Logistic Regression and Decision Tree produced substantially more false positives under the same recall requirement.
Clinically, these results suggest that XGBoost may be particularly valuable in settings where maximizing detection of disease progression is critical while still maintaining acceptable specificity and reducing unneccessary follow-up evaluations.
"""





"""**CONCLUSION**

The purpose of this study is to develop and evaluate predictive models to identify patients with MGUS and Smoldering multiple myeloma who are at increased risk of progressing to multiple myeloma.
This study aims to determine whether clinical and laboratory features can predict progression from MGUS or SMM to active multiple myeloma using supervised machine learning models.
My most important metric is recall for class 1 in the clinical setting, because we want to avoid missing patients who truly progress. The ROC_AUC is also very useful because it shows how well the model ranks high risk versus low-risk patients.
I also would like to take one step further, the next high impact improvement would be: tuning the decision threshold ( not just 0.5) and/or comparing models specifically on recall vs precision tradeoffs.

Given the clinical importance of not missing patients who will progress, model performance was evaluated at thresholds prioritizing high recall. At a selected operating point, the final model acchieved a recall of 0.85, indicating that approximately 85% of patients who progressed to multiple myeloma were correctly identified.

At this same threshold, the model achieved a precision of 0.70, meaning that 70% of patients identified as a high risk truly progressed, while 30% were false positives.  In a clinical context, these false positives may undergo closer monitoring which is generally acceptable compared to missing true progression cases.

Among the models evaluated, extreme gradient boosting demonstrated the best performance when evaluated at a clinically relevant recall threshold. At a decision threshold of 0.32, the model achieved a recall of 0.86 and a precision of 0.72, indicating that the majority of progression cases were correctly identified while maintaining a reasonable false positive rate.
"""